defmodule EDA.FlagsTest do
  @moduledoc """
  Every flags module answers the same calls, generated by `EDA.Flags` from Discord's table: the
  user, member, message, role, system channel and activity flags.
  """

  use ExUnit.Case, async: true

  import Bitwise

  doctest EDA.Message.Flags
  doctest EDA.Role.Flags
  doctest EDA.Guild.SystemChannelFlags
  doctest EDA.Activity.Flags
  doctest EDA.Message, only: [flags: 1, flag?: 2]
  doctest EDA.Role, only: [flags: 1, flag?: 2]
  doctest EDA.Guild, only: [system_channel_flags: 1, system_channel_flag?: 2]
  doctest EDA.Activity, only: [flags: 1, flag?: 2]

  @modules [
    EDA.User.Flags,
    EDA.Member.Flags,
    EDA.Message.Flags,
    EDA.Role.Flags,
    EDA.Guild.SystemChannelFlags,
    EDA.Activity.Flags
  ]

  for mod <- @modules do
    test "#{inspect(mod)} round-trips every flag it knows, and skips unknown bits" do
      mod = unquote(mod)
      all = mod.to_list((1 <<< 31) - 1)

      assert all != []
      assert all |> mod.to_bitset() |> mod.to_list() == all
      assert Enum.all?(all, &(mod.from_bit(mod.to_bit(&1)) == {:ok, &1}))
      assert mod.to_list(1 <<< 40) == []
      refute mod.has?(nil, hd(all))
      assert_raise FunctionClauseError, fn -> mod.to_bit(:not_a_flag) end
    end
  end

  test "the flags a message carries, read off the message itself" do
    message = EDA.Message.from_raw(%{"id" => "1", "flags" => 1 <<< 14 ||| 1 <<< 2})

    assert EDA.Message.flags(message) == [:suppress_embeds, :has_snapshot]
    assert EDA.Message.flag?(message, :has_snapshot)
    refute EDA.Message.flag?(message, :ephemeral)
    assert EDA.Message.flags(%{"flags" => 64}) == [:ephemeral]
    assert EDA.Message.flags(%EDA.Message{}) == []
  end

  test "the system channel's suppressed notices, read off the guild" do
    guild = EDA.Guild.from_raw(%{"id" => "1", "system_channel_flags" => 1 <<< 3})

    assert EDA.Guild.system_channel_flags(guild) == [:suppress_join_notification_replies]
    refute EDA.Guild.system_channel_flag?(guild, :suppress_join_notifications)
  end
end
